### ISSUE TITLE
老板打成jar包上传一下子呗

### ISSUE THREAD

**Issue by Jaschenn** [lzq603/xuanke#1]
打成jar包可以更方便的运行（记得包含依赖呀！）

**Comment by lzq603** [comment]
啊哈哈，我不知道怎么上传jar到Release，我把下载地址加到Readme.md了

**Comment by Jaschenn** [comment]
啊哈，一开始没有注意到
要是从最开始的时候就知道就好了
我还没有用过这个工具😂
就要毕业了
新生来了一定要宣传
